version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8-bullseye"
        NODE_VERSION: "16"

    volumes:
      - ..:/workspace:cached
    
    command: sleep infinity

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ..:/app

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  mariadb-data: null
